#! env bash

# Usage: gen-phx [appname]

# copy the phx-docker directory files
cp $PHOENIX_DOCKER_GENERATOR/{.env,Dockerfile,docker-compose.yml} . 

# Hostname needs to match the service name in docker-compose.yml,
# which in this case is "db".
sed -i -e 's/hostname: "localhost"/hostname: "db"/g' config/dev.exs

# run ecto.create inside the web container
docker-compose run web mix ecto.create

# run migrations, if they exist
docker-compose run web mix ecto.migrate